require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'db/seeds.rb'
    - 'bin/**/*'
    - 'config/initializers/carrierwave.rb'
    - 'config/puma.rb'

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
    Enabled: false

Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'

Metrics/BlockLength:
    Max: 40
    Exclude:
        - 'spec/**/*'