dist: bionic
language: ruby
rvm:
- 2.7.2
services:
- postgresql
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
cache:
  - bundler
env:
  global:
  - CF_USER=ccs-cdu-travis-deploy@crowncommercial.gov.uk
  - CF_ORG=ccs-document-upload
  - secure: "Be/4fuHCTabqlePdTTWJh4zuvjnb7NkVYrCbKGsaxloiAK46P+91cT1HGvsJLM/pDh3y25bMhxKS5Adfs5IQ9qnjRijRdHgwwP3J3SGcPA01G57whDk4sMpszlPy/LOquNxkCLbgCdhatNuIFt++myAHxa5fIx+Forn1qYoMryum7vmo15sonHjRecDLvkimf0CXvs4zxVa3n3tPsEZg8OkFpDvKTL9g1lJG3FyNkHhxBIVfzVAV8WOaHncq6qP1G9+gov0l4FYpyo9Ft0+IzvEfOQTJMrA/hqOTOTJdxfMBMS2HB4IybiQrspUw2ZGfK5xMEXz/Wi+dXHHyOBYiiseKSTPAJjDLfDLo4bCYqFtQpa/L/QOTebT/UJkstX4NMPNMlREfZjm1m3NNX180bmv5ZdLFj6clXnIkAWlsAzxI6sNCrZLLIvk0DHF7c0VueAk15EIshmh4aDTfmvCgmhpdrqdgubLtnczZviwKj0EgINRq8/OxHxJKbF81eUm4vVx6h4wZN+9F4rMLR7BJ1w7zKC3p7DxZrbWwwZ9bERU5KP/giKKvEbCDfX582XnrUxPPMC6mCqOOwaWIUZ7uWdYxFxYzWV6om2vsV9MJNOHuly8GkrAQJI1I6vrbXTozo1zMjUlCx8WmSlZcN9Jx5m5832AJqDH81Oj9+nRNwyk="
before_install:
  - gem install bundler -v 2.1.4
install:
  - bundle install --jobs=3 --retry=3
before_script:
  - psql -c 'create database ccs_conclave_document_upload_test;' -U postgres
  - bundle exec rails db:migrate
before_deploy:
  - echo "install cloudfoundry cli"
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get update -qq
  - sudo apt-get install cf-cli
  - cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
  - cf install-plugin blue-green-deploy -f -r CF-Community
deploy:
  - provider: script
    script: bash deploy-app.sh -u $CF_USER -o $CF_ORG -p $CF_PASS -s "sandbox"
    # on:
    #   branch: sandbox
