dist: bionic
language: ruby
rvm:
- 2.7.2
services:
- postgresql
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
cache:
  - bundler
env:
  global:
  - CF_ORG=ccs-document-upload
  #CF_USER
  - secure: "xhJtJZ5ggRfiZY9n51eVLMAoOT/05DdjoBJYMMRM7JUhuZLtyj3lWluR3P4ywHTLoHIzQk8ymx+vwQxy4dr3d/zoBRZqndbLIvbV0eKboTDDRx51vU8bvQbrr2PX9nMU4rdr2RbLDIXADo/cho6XZCRgsQ8NDMtTo4T/b9vdS1Ggh9rV/u+w0h4WEylVzAgCevMGXlP99vNdLlNXVsHT1gznC7oyqiOlvAgdYVAeS491uQrVuMEfHuOMuRBCNtAEYNSYh0GKuLlWcuSkEe7+VmDGkUJ5cO9dCVQIxC2RQfcC/5AORG+0CI2pP4t1dYxKIuDVc3Jz1yjYiT98xjvzr/zPpZBRnL1kVbic+iWqVtJtGNGNtPJIyH8ZidvPwmP/3ljraEh7XgNsEL5iObAkMTqbNEcleYbw/adKUXkZJd8d5Dj3UiL5Tf7EMSaofOdifFJcpbQN2zoGE+KLB7AVcQqa/tiXmRf7u1QcMAu2AJxJXY9CNRTyeYZWDqUA4Vzf2KXVDdQmVkPtF/OFFMYJ6uc0XOJQUpvAWOUMe/yGLHlWILXlM4RhcNsFpkuwPY/4uj4GEzjTG9rFs4YR7AAowhQGA4HY1zdoH2bbCTo1+w9Oj7wH+qIUP9VYlC+v26vXAg5Buaz91oxJfi+x57uitO6mw+EpDbIgdjlgCyQkBTY="
  #CF_PASS
  - secure: "fN9Ny+LrzbbhdHf0kvpY+yDD95EIf5iBFUQ8pNggmleTwrh7TTDua1oByiy+lVqiAMaU6koBlosQR9NuogdeoRQMZ8q9ylS+MBt9qGq5oZYPCSM5bCnuxyWSzAjpHKtgawdn3IdMuuVj/0Yqk3L7W3uf/0y0pJxpg5OjJrYuW/Hz3zX8vI9K7QRYXgWhyV8zidYvas27IlgXZr/TKlh+4XUIZHl1w8T2SY3XejTVYMMzeUvmoCwdQMa8UvGVXe436mL6EepLLt3ERh08hq9J1y9gJfu9zOqVRq8epFJdpDGQJMNihWFaDNmF7/BqVcurL/JJII1HxRMItq8z4aTDGsFN3TsqL0Tqfds/oogQmcIgosaAJSkwRaD4HG3t+UyxQp1VfiHQyyXtFR3o5K9uKv2oBE6dq0hyrVYYSBXES337nC9Ud0uXeEI+v1X6rHfcyw/+PvHTy9EqKhe21/6BuZpRupCsgYsJrMNDcec6pePG57HkjeJ/k/b00P3a/3qo/q9xIiUZ3QdCguO+hWCBE0s+4k2b4tky0dYVW3yP522e0TdLmWEmSqf/kjx0SPFEKBbHkYxmxWwiRnmk6IrNeeu6cvMitoLl1nBUZuTqaZpB5aZi9sG8yhF4MsMbP9PWkqzkjbuQ18JsLS+HiPqYVC4KaShxyPSYfsy7RMyRR+s="
before_install:
  - gem install bundler -v 2.1.4
install:
  - bundle install --jobs=3 --retry=3
before_script:
  - psql -c 'create database ccs_conclave_document_upload_test;' -U postgres
  - bundle exec rails db:migrate
before_deploy:
  - echo "install cloudfoundry cli"
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get update -qq
  - sudo apt-get install cf-cli
deploy:
  - provider: script
    script: bash deploy-app.sh -u $CF_USER -o $CF_ORG -p $CF_PASS -s sandbox
    on:
      branch: sandbox
