dist: bionic
language: ruby
rvm:
- 2.7.2
services:
- postgresql
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
cache:
  - bundler
env:
  global:
  - CF_USER=ccs-cdu-travis-deploy@crowncommercial.gov.uk
  - CHECK_ENDPOINT_URL=localhost:3000/document-check
  - AUTH_TOKEN=test
  - CF_ORG=ccs-document-upload
  - secure: "gjODf9ho+cAZNhQ+VUf1G1HvkEGeCNfRRBMEqK42SM2T/Ppcw8r8NbmVW+tOuXzRIRuGLAkLvdXc4/rVbiJcYZUG4v2PMGlV4cwp0/w484TFwoK+rJSIDMrMaKI498+yEVhN3XeRfmqyoqTxRLV3J8QuULOdZej5imX3jGrIFSxYGVhzMG7NwX6wXg5hEZvwU6NI65JHzIRYa0RnI43YrwCNRQeciaRkx25Kyl79wJtXkv/wooYtbHerB06cOrEjB1kRTFvNVvQSbVWzHNUxwsuk1sIaoHY1sg4qdeN8YsnPK+aykjxXtHObweC7BwZw1D6h/rer6ZYLmWtMldKzgjFR7e6dXgeXIpfhd7Gfrgr8M7+IlFIQfvCXFCn7ruxGQpF/t+ZmVbHxgH7CS84AAwdKOwfis9GORdVKIEwAdkBNQkhPtSWwTO6zQCTmYpTYUkUl/h5bIQb/HKu6P2UOTyk5U0DOpI4guy1syD0JXm+UP7ETTJiVH0Lf/UyE5kumRdj2NBgHakcVIxYUo9B5Wywwf/mhsbX6oc37l+665FAqZUdNQ55iXT6vLObAWgH8RQ6731EW3iMHg/I9m9yCQ7l9gQ4qNd3HhRJviJzAqaZZSmzoJY1pm6GUJP8k/j8hQl8GaI9GJTNqJuixoEEBgeyLR2LMpBDQFXHj5lyUB8M="
before_install:
  - gem install bundler -v 2.1.4
install:
  - bundle install --jobs=3 --retry=3
before_script:
  - psql -c 'create database ccs_conclave_document_upload_test;' -U postgres
  - bundle exec rails db:migrate
before_deploy:
  - echo "install cloudfoundry cli"
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get update -qq
  - sudo apt-get install cf-cli
  - cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
  - cf install-plugin blue-green-deploy -f -r CF-Community
deploy:
  - provider: script
    script: bash deploy-app.sh -u $CF_USER -o $CF_ORG -p $CF_PASS -s sandbox
    on:
      branch: sandbox
