dist: bionic
language: ruby
rvm:
- 2.7.2
services:
- postgresql
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
cache:
  - bundler
env:
  global:
  - CF_ORG=ccs-document-upload
  #CF_USER
  - secure: xhJtJZ5ggRfiZY9n51eVLMAoOT/05DdjoBJYMMRM7JUhuZLtyj3lWluR3P4ywHTLoHIzQk8ymx+vwQxy4dr3d/zoBRZqndbLIvbV0eKboTDDRx51vU8bvQbrr2PX9nMU4rdr2RbLDIXADo/cho6XZCRgsQ8NDMtTo4T/b9vdS1Ggh9rV/u+w0h4WEylVzAgCevMGXlP99vNdLlNXVsHT1gznC7oyqiOlvAgdYVAeS491uQrVuMEfHuOMuRBCNtAEYNSYh0GKuLlWcuSkEe7+VmDGkUJ5cO9dCVQIxC2RQfcC/5AORG+0CI2pP4t1dYxKIuDVc3Jz1yjYiT98xjvzr/zPpZBRnL1kVbic+iWqVtJtGNGNtPJIyH8ZidvPwmP/3ljraEh7XgNsEL5iObAkMTqbNEcleYbw/adKUXkZJd8d5Dj3UiL5Tf7EMSaofOdifFJcpbQN2zoGE+KLB7AVcQqa/tiXmRf7u1QcMAu2AJxJXY9CNRTyeYZWDqUA4Vzf2KXVDdQmVkPtF/OFFMYJ6uc0XOJQUpvAWOUMe/yGLHlWILXlM4RhcNsFpkuwPY/4uj4GEzjTG9rFs4YR7AAowhQGA4HY1zdoH2bbCTo1+w9Oj7wH+qIUP9VYlC+v26vXAg5Buaz91oxJfi+x57uitO6mw+EpDbIgdjlgCyQkBTY=
  #CF_PASS
  - secure: QPomowEvM3Q9DvOToruLTuwbTnFR061H4p3dfs529AB+GWz5p8fV18MV+Ej1t2q7lomgmMoSKNi4ctK+gSjjLV7LV3KD8I9HFH6uxFkkyBGtLKniWxGptnSeMUf9Xx/ht+0VpsKxsLL5EzgLrkbBcUKvS6Um9RNl6Wf/SVXRM+U2Wrf2N2kCbes/Ynm9CkyXrO/ZY+1loF3bWgABgCpBVYq6dI+R/RPzIuAjI48nIZwTvmisZIEoMxvU5QJS1xdyJg1CygP4A4p/0aH+bUunr6/a46uOMhHJ8Cj7jcs+wP2CcKUOpmQK124uaZ7YQCZCRZqwQpHIkFaT3ZI5WqkaO/juJ2WRzK7Yu5We+uLoLufM0pKlBz+wWfqEM18V2g3Sq1DYhYC9/FgzMcm4si96lMj3l5tzkBYAhxMrgklE2Y64+E0fgXKtKcNESZSagylFHcluDxuyOF5oy4jp+eIOVXwJtFkT+Plwy+LfikJcQnDyTxhlAferkwT8KJYo/tPvKMpVkApIYV1LxgbiFBlpZ6Xxy1IpmK+xQwudsCaqRkxqkMcVVFhOGtKaToIF3T64N5NUaLjAVUcVxY/JdfUOUm1PIMF9P3GKON7rVgybmRT7u5JodS6l4OI4EUphGXbV7UmnUQFn9ZHQ3gYfnuR9ieOkIMVDvuH6po1GM8qF5HE=
before_install:
  - gem install bundler -v 2.1.4
install:
  - bundle install --jobs=3 --retry=3
before_script:
  - bundle exec rails db:migrate RAILS_ENV=test
deploy:
  provider: cloudfoundry
  api: "$API_URI"
  username: "$USERNAME"
  password: "$CF_PASS"
  organization: "$CF_ORG"
  space: $SPACE"
  on:
    branch: sandbox
