---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  generateName: buildkit-
  labels:
    app.kubernetes.io/name: ccs-conclave-document-upload
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2
