---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: buildkit-
spec:
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/buildkit: unconfined
    # see buildkit/docs/rootless.md for caveats of rootless mode
    spec:
      restartPolicy: Never
      initContainers:
        - name: chown
          image: alpine:3.10
          command:
            - sh
            - -c
            - "chown -R 1000:1000 /home/user/.local/share/buildkit"
          securityContext:
            capabilities:
              add:
                - chown
            privileged: true
          volumeMounts:
            - mountPath: /home/user/.local/share/buildkit
              name: buildkitd
        - name: receive-archive
          image: alpine:3.10
          command:
            - sh
            - -c
            - sleep 30
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: repo
              mountPath: /tmp
        - name: extract
          image: alpine:3.10
          command:
            - sh
            - -c
            - "tar -zvxf /tmp/repo.tar.gz -C /workspace"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: workspace
              mountPath: /workspace
            - name: repo
              mountPath: /tmp
        # Use for debugging the previous initContainers
        # - name: sh
        #   image: alpine:3.10
        #   command:
        #     - sh
        #     - -c
        #     - "tail -f /dev/null"
        #   securityContext:
        #     runAsUser: 1000
        #     runAsGroup: 1000
        #   volumeMounts:
        #     - name: workspace
        #       mountPath: /workspace
      containers:
        - name: buildkit
          image: moby/buildkit:master-rootless
          env:
            - name: BUILDKITD_FLAGS
              value: --oci-worker-no-process-sandbox
          command:
            - buildctl-daemonless.sh
          args:
            - build
            - --frontend
            - dockerfile.v0
            - --local
            - context=/workspace
            - --local
            - dockerfile=/workspace
          # To push the image to a registry, add
          # `--output type=image,name=docker.io/username/image,push=true`
          securityContext:
            capabilities:
              add:
                - chown
            # Needs Kubernetes >= 1.19
            seccompProfile:
              type: Unconfined
            # To change UID/GID, you need to rebuild the image
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: workspace
              readOnly: true
              mountPath: /workspace
            # Dockerfile has `VOLUME /home/user/.local/share/buildkit` by default too,
            # but the default VOLUME does not work with rootless on Google's Container-Optimized OS
            # as it is mounted with `nosuid,nodev`.
            # https://github.com/moby/buildkit/issues/879#issuecomment-1240347038
            - mountPath: /home/user/.local/share/buildkit
              name: buildkitd
      # To push the image, you also need to create `~/.docker/config.json` secret
      # and set $DOCKER_CONFIG to `/path/to/.docker` directory.
      volumes:
        - name: workspace
          emptyDir: {}
        - name: buildkitd
          persistentVolumeClaim:
            claimName: bar
        - name: repo
          emptyDir: {}
