---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: buildkit-
  labels:
    app.kubernetes.io/name: ccs-conclave-document-upload
spec:
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/buildkit: unconfined
    # see buildkit/docs/rootless.md for caveats of rootless mode
    spec:
      securityContext:
        fsGroup: 1000
      serviceAccount: jenkins-agent
      restartPolicy: Never
      initContainers:
        - name: started
          image: alpine:3.10
          command:
            - sh
            - -c
            - "true"
        - name: receive-archive
          image: alpine:3.10
          command:
            - sh
            - -c
            - sleep 30
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: repo
              mountPath: /tmp
        - name: extract-archive
          image: alpine:3.10
          command:
            - sh
            - -c
            - "tar -zvxf /tmp/repo.tar.gz -C /workspace"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: workspace
              mountPath: /workspace
            - name: repo
              mountPath: /tmp
        # Does an ECR login so that the image can be pushed
        # TODO: Change this to a custom image that includes aws-cli and docker, so we don't need
        # to install anything at runtime, which requires running as root, yuck!
        # - name: aws-ecr-login
        #   image: docker:latest
        #   command:
        #     - sh
        #     - -c
        #     - >-
        #       apk add aws-cli && aws ecr get-login-password --region eu-west-2 |
        #       docker --config /docker login
        #       --username AWS --password-stdin 473251818902.dkr.ecr.eu-west-2.amazonaws.com
        #       && chmod 640 /docker/config.json
        #   # securityContext:
        #   #   runAsUser: 1000
        #   #   runAsGroup: 1000
        #   volumeMounts:
        #     - name: docker-config
        #       mountPath: /docker
        - name: aws-ecr-cred-helper-login
          image: alpine:3.10
          command:
            - sh
            - -c
            - >-
              wget
              https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/0.7.1/linux-amd64/docker-credential-ecr-login
              -O /usr/local/bin/docker-credential-ecr-login && chmod +x /usr/local/bin/docker-credential-ecr-login &&
              echo '{ "credsStore": "ecr-login", "credHelpers": { "public.ecr.aws": "ecr-login", "473251818902.dkr.ecr.eu-west-2.amazonaws.com": "ecr-login" } }' > /docker/config.json
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: docker-config
              mountPath: /docker
            - name: local-bin
              mountPath: /usr/local/bin
        # Use for debugging the previous initContainers
        # - name: sh
        #   image: alpine:3.10
        #   command:
        #     - sh
        #     - -c
        #     - "tail -f /dev/null"
        #   securityContext:
        #     runAsUser: 1000
        #     runAsGroup: 1000
        #   volumeMounts:
        #     - name: workspace
        #       mountPath: /workspace
      containers:
        - name: buildkit
          image: moby/buildkit:master-rootless
          env:
            - name: BUILDKITD_FLAGS
              value: --oci-worker-no-process-sandbox
          command:
            - buildctl-daemonless.sh
          args:
            - build
            - --frontend
            - dockerfile.v0
            - --local
            - context=/workspace
            - --local
            - dockerfile=/workspace
            - --output
            - type=image,name=473251818902.dkr.ecr.eu-west-2.amazonaws.com/document-upload:TAG_PLACEHOLDER,push=true
          # To push the image to a registry, add
          # `--output type=image,name=docker.io/username/image,push=true`
          securityContext:
            # TODO: Remove once confirm not required
            capabilities:
              add:
                - chown
            # Needs Kubernetes >= 1.19
            seccompProfile:
              type: Unconfined
            # To change UID/GID, you need to rebuild the image
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            # Dockerfile has `VOLUME /home/user/.local/share/buildkit` by default too,
            # but the default VOLUME does not work with rootless on Google's Container-Optimized OS
            # as it is mounted with `nosuid,nodev`.
            # https://github.com/moby/buildkit/issues/879#issuecomment-1240347038
            - name: buildkit
              mountPath: /home/user/.local/share/buildkit
            - name: docker-config
              mountPath: /home/user/.docker
            - name: local-bin
              mountPath: /usr/local/bin
            - name: workspace
              readOnly: true
              mountPath: /workspace
      volumes:
        - name: buildkit
          persistentVolumeClaim:
            claimName: PLACEHOLDER
        - name: docker-config
          emptyDir: {}
        - name: local-bin
          emptyDir: {}
        - name: repo
          emptyDir: {}
        - name: workspace
          emptyDir: {}
