---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  generateName: buildkit-
  # name: buildkit-workspace
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2
