name: CXI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:14-3.2
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ccs_conclave_document_upload_test
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/ccs_conclave_document_upload_test
      CORS_ORIGINS: "http://localhost:3000"

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libpq-dev postgresql-client

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.4
          bundler-cache: false

      - name: Setup DB
        run: |
          bundle exec rails db:drop || true
          bundle exec rails db:create db:schema:load --trace

      - name: Run migrations
        run: bundle exec rails db:migrate RAILS_ENV=test

      - name: Run tests
        run: bundle exec rspec

      - name: Run rubocop
        run: bundle exec rubocop
